/-
  AMO-Lean: Full Pipeline
  ========================

  Exercises the complete AMO-Lean pipeline end-to-end:

    1. E-Graph optimization (simplify a butterfly expression)
    2. Matrix algebra → Sigma-SPL IR → C code generation
    3. Matrix algebra → Sigma-SPL IR → Rust code generation
    4. ExpandedSigma → Trust-Lean verified C code generation

  The target transform is DFT_4 (Walsh-Hadamard Transform of size 4).

  Usage:
    lake env lean AmoLean/FullPipeline.lean
    cd generated && clang -O2 -o dft4 dft4.c && rustc -o dft4_rs dft4.rs && cd ..
    python3 integration_tests/verify_dft4.py --binary generated/dft4 integration_tests/test_vectors.txt
    python3 integration_tests/verify_dft4.py --binary generated/dft4_rs integration_tests/test_vectors.txt
-/

import AmoLean.Basic
import AmoLean.CodeGen
import AmoLean.EGraph.Optimize
import AmoLean.Sigma.Basic
import AmoLean.Sigma.Expand
import AmoLean.Sigma.CodeGen
import AmoLean.Backends.Rust
import AmoLean.Bridge.TrustLean

namespace AmoLean.FullPipeline

open AmoLean (Expr)
open AmoLean.Expr (var const add mul simplify)
open AmoLean.EGraph.Optimize (optimizeExpr OptStats countOps)
open AmoLean.Matrix (MatExpr)
open AmoLean.Sigma (lowerFresh expandSigmaExpr ExpandedSigma)
open AmoLean.Sigma.CodeGen (matExprToC generateFunction generateCFile)
open AmoLean.Backends.Rust (matExprToRust generateRustFile generateNttFieldTrait)
open AmoLean.Bridge.TrustLean (verifiedCodeGen verifiedCodeGenMicroC)

-- ============================================================================
-- Part 1: E-Graph Optimization Demo
-- ============================================================================

/-- Optimize a butterfly expression where twiddle = 1.
    Demonstrates: (a + b * 1) simplifies to (a + b) -/
def optimizeButterflyExpr : IO Unit := do
  let a := var 0
  let b := var 1
  let expr : Expr Int := add a (mul b (const 1))
  let (optimized, stats) := optimizeExpr expr

  IO.println "── E-Graph Optimization ──────────────────────────"
  IO.println s!"  Before: a + b * 1  ({stats.opsBefore} ops)"
  IO.println s!"  After:  {repr optimized}  ({stats.opsAfter} ops)"
  IO.println s!"  Saved {stats.opsBefore - stats.opsAfter} operation(s)"

  let cBefore := AmoLean.exprToC "butterfly_naive" ["a", "b"] expr
  let cAfter := AmoLean.exprToC "butterfly_optimized" ["a", "b"] (add a b)
  IO.println ""
  IO.println "  Naive C:"
  IO.println s!"    {cBefore}"
  IO.println "  Optimized C:"
  IO.println s!"    {cAfter}"
  IO.println ""

-- ============================================================================
-- Part 2: DFT_4 Code Generation via Sigma-SPL
-- ============================================================================

/-- The DFT_4 matrix expression -/
def dft4Expr : MatExpr Int 4 4 := .dft 4

/-- Generate C code for DFT_4 using the Sigma-SPL pipeline.
    Uses: matExprToC from AmoLean.Sigma.CodeGen -/
def generateDFT4C : IO String := do
  let code := matExprToC "dft4" 4 4 dft4Expr
  IO.println "── DFT_4 C Code (Sigma-SPL Pipeline) ──────────────"
  IO.println code
  IO.println ""
  return code

/-- Generate Rust code for DFT_4 using the Sigma-SPL pipeline.
    Uses: generateNttFieldTrait + generateFunction from AmoLean.Backends.Rust -/
def generateDFT4Rust : IO String := do
  let sigma := lowerFresh 4 4 dft4Expr
  let expanded := expandSigmaExpr sigma
  let trait := generateNttFieldTrait
  let func := AmoLean.Backends.Rust.generateFunction "dft4" 4 4 expanded
  let code := "// Generated by AMO-Lean Sigma-SPL Rust CodeGen\n\n" ++
    "use std::fmt::Debug;\nuse std::ops::{Add, Sub, Mul, Neg};\n\n" ++
    trait ++ "\n\n" ++ func
  IO.println "── DFT_4 Rust Code (Sigma-SPL Pipeline) ───────────"
  IO.println s!"  Generated {code.length} chars"
  IO.println s!"  Includes: NttField trait + dft4 function"
  IO.println ""
  return code

/-- Generate verified C code for DFT_4 using the Trust-Lean bridge.
    Uses: verifiedCodeGen from AmoLean.Bridge.TrustLean -/
def generateDFT4Verified : IO (Option String) := do
  let sigma := lowerFresh 4 4 dft4Expr
  let expanded := expandSigmaExpr sigma
  let verified := verifiedCodeGen expanded
  IO.println "── DFT_4 Verified C Code (Trust-Lean) ─────────────"
  match verified with
  | some code =>
    IO.println code
    IO.println ""
  | none =>
    IO.println "  (conversion failed — non-standard variable names)"
    IO.println ""
  return verified

-- ============================================================================
-- Part 3: Write Compilable Files
-- ============================================================================

/-- Minimal C test harness — applies kernel to command-line arguments.
    The kernel function is generated by the Sigma-SPL pipeline above.
    Test vector iteration is handled by verify_dft4.py. -/
def cTestHarness (kernelName : String) (size : Nat) : String :=
  let printFmt := String.intercalate " " (List.replicate size "%lld")
  let printArgs := String.intercalate ", " (List.range size |>.map fun i => s!"(long long)out[{i}]")
  "\n/* Minimal harness — applies kernel to command-line arguments */\n" ++
  "#include <stdio.h>\n#include <stdlib.h>\n\n" ++
  "int main(int argc, char* argv[]) {\n" ++
  s!"    if (argc != {size + 1}) " ++ "{ fprintf(stderr, \"Usage: %s" ++
  String.intercalate "" (List.replicate size " <x>") ++
  "\\n\", argv[0]); return 1; }\n\n" ++
  s!"    double inp[{size}], out[{size}];\n" ++
  s!"    for (int i = 0; i < {size}; i++) inp[i] = (double)atoll(argv[i+1]);\n" ++
  s!"    {kernelName}(inp, out);\n" ++
  s!"    printf(\"{printFmt}\\n\", {printArgs});\n" ++
  "    return 0;\n}\n"

/-- Minimal Rust test harness: F64 wrapper + main that applies kernel to CLI args.
    The NttField trait and kernel are generated by the pipeline.
    Test vector iteration is handled by verify_dft4.py. -/
def rustTestHarness (kernelName : String) (size : Nat) : String :=
  let f64Wrap := String.intercalate ", " (List.range size |>.map fun i => s!"F64(vals[{i}] as f64)")
  let outArgs := String.intercalate ", " (List.range size |>.map fun i => s!"output[{i}].0 as i64")
  let fmtSpec := String.intercalate " " (List.replicate size "{}")
  "\n// ── Test scaffolding (not generated by pipeline) ──────────\n\n" ++
  "#[derive(Copy, Clone, Debug)]\nstruct F64(f64);\n\n" ++
  "impl NttField for F64 {\n" ++
  "    const MODULUS: u64 = 0;\n" ++
  "    const GENERATOR: u64 = 0;\n" ++
  "    fn zero() -> Self { F64(0.0) }\n" ++
  "    fn one() -> Self { F64(1.0) }\n" ++
  "    fn from_u64(n: u64) -> Self { F64(n as f64) }\n" ++
  "    fn to_u64(self) -> u64 { self.0 as u64 }\n" ++
  "    fn add(self, other: Self) -> Self { F64(self.0 + other.0) }\n" ++
  "    fn sub(self, other: Self) -> Self { F64(self.0 - other.0) }\n" ++
  "    fn mul(self, other: Self) -> Self { F64(self.0 * other.0) }\n" ++
  "    fn neg(self) -> Self { F64(-self.0) }\n" ++
  "    fn inv(self) -> Self { F64(1.0 / self.0) }\n" ++
  "    fn pow(self, exp: u64) -> Self { F64(self.0.powi(exp as i32)) }\n" ++
  "    fn primitive_root(_n: usize) -> Self { F64(1.0) }\n" ++
  "}\n\n" ++
  "impl Default for F64 { fn default() -> Self { F64(0.0) } }\n" ++
  "impl PartialEq for F64 { fn eq(&self, other: &Self) -> bool { self.0 == other.0 } }\n\n" ++
  "impl std::ops::Add for F64 { type Output = Self; fn add(self, rhs: Self) -> Self { F64(self.0 + rhs.0) } }\n" ++
  "impl std::ops::Sub for F64 { type Output = Self; fn sub(self, rhs: Self) -> Self { F64(self.0 - rhs.0) } }\n" ++
  "impl std::ops::Mul for F64 { type Output = Self; fn mul(self, rhs: Self) -> Self { F64(self.0 * rhs.0) } }\n" ++
  "impl std::ops::Neg for F64 { type Output = Self; fn neg(self) -> Self { F64(-self.0) } }\n\n" ++
  "fn main() {\n" ++
  "    let args: Vec<String> = std::env::args().collect();\n" ++
  s!"    if args.len() != {size + 1} " ++ "{\n" ++
  "        eprintln!(\"Usage: " ++ "{}" ++ s!" <x0>..<x{size - 1}>\", args[0]);\n" ++
  "        std::process::exit(1);\n" ++
  "    }\n\n" ++
  "    let vals: Vec<i64> = args[1..].iter().map(|s| s.parse().unwrap()).collect();\n" ++
  s!"    let input = [{f64Wrap}];\n" ++
  s!"    let mut output = [F64(0.0); {size}];\n" ++
  s!"    {kernelName}(&input, &mut output);\n" ++
  s!"    println!(\"{fmtSpec}\", {outArgs});\n" ++
  "}\n"

/-- Write C file: pipeline-generated kernel + test harness -/
def writeCFile (kernelCode : String) : IO Unit := do
  let contents := kernelCode ++ "\n" ++ cTestHarness "dft4" 4
  IO.FS.writeFile "generated/dft4.c" contents

/-- Write Rust file: pipeline-generated code (NttField trait + kernel) + test harness -/
def writeRustFile (rustCode : String) : IO Unit := do
  let contents := rustCode ++ "\n" ++ rustTestHarness "dft4" 4
  IO.FS.writeFile "generated/dft4.rs" contents

-- ============================================================================
-- Part 4: Run the Full Pipeline
-- ============================================================================

def runFullPipeline : IO Unit := do
  IO.println "╔══════════════════════════════════════════════════════════════╗"
  IO.println "║  AMO-Lean Full Pipeline: Optimize → Generate → Verify      ║"
  IO.println "╚══════════════════════════════════════════════════════════════╝"
  IO.println ""

  -- Step 1: E-Graph optimization demo
  optimizeButterflyExpr

  -- Step 2: Generate DFT_4 code via all three pipelines
  let cKernel ← generateDFT4C
  let rustCode ← generateDFT4Rust
  let _verified ← generateDFT4Verified

  -- Step 3: Write compilable files
  IO.println "── Writing Files ────────────────────────────────"
  writeCFile cKernel
  IO.println "  Wrote generated/dft4.c"
  writeRustFile rustCode
  IO.println "  Wrote generated/dft4.rs"
  IO.println ""

  -- Step 4: Instructions
  IO.println "── Next Steps ─────────────────────────────────────"
  IO.println "  cd generated && clang -O2 -o dft4 dft4.c && rustc -o dft4_rs dft4.rs && cd .."
  IO.println "  python3 integration_tests/verify_dft4.py --binary generated/dft4 integration_tests/test_vectors.txt"
  IO.println "  python3 integration_tests/verify_dft4.py --binary generated/dft4_rs integration_tests/test_vectors.txt"
  IO.println ""

#eval! runFullPipeline

-- ============================================================================
-- Part 5: Tests — Verify codegen output within Lean
-- ============================================================================

section Tests

/-- Helper: check that a string contains a substring -/
def assertContains (haystack : String) (needle : String) (msg : String) : IO Unit := do
  if (haystack.splitOn needle).length <= 1 then
    throw (IO.userError s!"FAIL: {msg} — expected to find '{needle}'")

/-- Helper: check that a string does NOT contain a substring -/
def assertNotContains (haystack : String) (needle : String) (msg : String) : IO Unit := do
  if (haystack.splitOn needle).length > 1 then
    throw (IO.userError s!"FAIL: {msg} — did not expect to find '{needle}'")

/-- Test: E-graph optimization reduces ops -/
def testEGraphOptimization : IO Unit := do
  let expr : Expr Int := add (var 0) (mul (var 1) (const 1))
  let (_optimized, stats) := optimizeExpr expr
  if stats.opsAfter >= stats.opsBefore then
    throw (IO.userError s!"FAIL: E-graph should reduce ops ({stats.opsBefore} → {stats.opsAfter})")
  IO.println "  PASS: E-graph optimization reduces operations"

/-- Test: matExprToC generates valid C with expected structure -/
def testCCodeGen : IO Unit := do
  let code := matExprToC "dft4" 4 4 dft4Expr
  assertContains code "void dft4" "C function signature"
  assertContains code "restrict" "restrict keyword for aliasing"
  assertContains code "double" "double type for field elements"
  assertContains code "#include" "includes present"
  assertContains code "in[" "input array access"
  assertContains code "out[" "output array access"
  IO.println "  PASS: C codegen produces valid DFT_4 function"

/-- Test: matExprToRust generates valid Rust with NttField trait -/
def testRustCodeGen : IO Unit := do
  -- Test the full matExprToRust (includes Goldilocks, BabyBear)
  let fullCode := matExprToRust "dft4" 4 4 dft4Expr
  assertContains fullCode "pub trait NttField" "NttField trait"
  assertContains fullCode "pub fn dft4" "Rust function signature"
  assertContains fullCode "Goldilocks" "Goldilocks field implementation"
  assertContains fullCode "BabyBear" "BabyBear field implementation"
  assertContains fullCode "input[" "input slice access"
  assertContains fullCode "output[" "output slice access"
  -- Test generateNttFieldTrait independently
  let trait := generateNttFieldTrait
  assertContains trait "NttField" "trait name"
  assertContains trait "fn zero" "zero constructor"
  assertContains trait "fn primitive_root" "primitive_root method"
  IO.println "  PASS: Rust codegen produces valid DFT_4 with NttField"

/-- Test: verified codegen via Trust-Lean succeeds for DFT_4 -/
def testVerifiedCodeGen : IO Unit := do
  let sigma := lowerFresh 4 4 dft4Expr
  let expanded := expandSigmaExpr sigma
  match verifiedCodeGen expanded with
  | some code =>
    if code.isEmpty then
      throw (IO.userError "FAIL: verifiedCodeGen returned empty string")
    IO.println s!"  PASS: Trust-Lean verified codegen succeeded ({code.length} chars)"
  | none =>
    throw (IO.userError "FAIL: verifiedCodeGen returned none for DFT_4")

/-- Test: DFT_2 generates correct butterfly pattern -/
def testDFT2Butterfly : IO Unit := do
  let dft2 : MatExpr Int 2 2 := .dft 2
  let code := matExprToC "butterfly_2" 2 2 dft2
  assertContains code "void butterfly_2" "function name"
  -- DFT_2 should have add and sub: y[0] = x[0]+x[1], y[1] = x[0]-x[1]
  assertContains code "+" "addition in butterfly"
  assertContains code "-" "subtraction in butterfly"
  IO.println "  PASS: DFT_2 generates correct butterfly structure"

/-- Test: Kronecker product I_2 ⊗ DFT_2 generates a loop -/
def testKroneckerLoop : IO Unit := do
  let i2 : MatExpr Int 2 2 := .identity 2
  let dft2 : MatExpr Int 2 2 := .dft 2
  let expr : MatExpr Int 4 4 := .kron i2 dft2
  let sigma := lowerFresh 4 4 expr
  let expanded := expandSigmaExpr sigma
  let code := AmoLean.Sigma.CodeGen.generateFunction "kron_test" 4 4 expanded
  assertContains code "for" "loop from Kronecker product"
  IO.println "  PASS: I_2 ⊗ DFT_2 generates loop structure"

/-- Test: exprToC pipeline for scalar expressions -/
def testScalarExprToC : IO Unit := do
  -- (x + 0) * 1 should simplify to just x
  let expr : Expr Int := mul (add (var 0) (const 0)) (const 1)
  let code := AmoLean.exprToC "identity_opt" ["x"] expr
  assertContains code "int64_t identity_opt" "function signature"
  assertContains code "return" "return statement"
  IO.println "  PASS: Scalar exprToC generates valid C function"

/-- Test: C and Rust codegen produce equivalent kernel structure -/
def testCRustEquivalence : IO Unit := do
  let cCode := matExprToC "dft4" 4 4 dft4Expr
  let rustCode := matExprToRust "dft4" 4 4 dft4Expr
  -- Both should have the same number of temporary variables
  let cTemps := (cCode.splitOn "double t").length - 1
  let rustTemps := (rustCode.splitOn "let t").length - 1
  if cTemps != rustTemps then
    throw (IO.userError s!"FAIL: C has {cTemps} temps but Rust has {rustTemps}")
  IO.println s!"  PASS: C and Rust codegen produce {cTemps} temporaries each"

/-- Test: Trust-Lean roundtrip for DFT_4 expanded sigma -/
def testTrustLeanRoundtrip : IO Unit := do
  let sigma := lowerFresh 4 4 dft4Expr
  let expanded := expandSigmaExpr sigma
  let converted := AmoLean.Bridge.TrustLean.convertExpandedSigma expanded
  if converted.isNone then
    throw (IO.userError "FAIL: convertExpandedSigma returned none for DFT_4")
  IO.println "  PASS: Trust-Lean bridge conversion succeeds for DFT_4"

/-- Run all tests -/
def runTests : IO Unit := do
  IO.println "── Tests ────────────────────────────────────────"
  testEGraphOptimization
  testCCodeGen
  testRustCodeGen
  testVerifiedCodeGen
  testDFT2Butterfly
  testKroneckerLoop
  testScalarExprToC
  testCRustEquivalence
  testTrustLeanRoundtrip
  IO.println "  ────────────────────────────────────────────────"
  IO.println "  All 9 tests passed"
  IO.println ""

#eval! runTests

end Tests

end AmoLean.FullPipeline
