/* Test harness for NTT kernels generated by trzk.
 *
 * Reads N int32 values from argv, computes twiddles, runs the NTT,
 * and prints the N-element output.
 *
 * Set via -D at compile time:
 *   -DNTT_FUNC=babybear_ntt_plan   (generated function name)
 *   -DNTT_SIZE=16                   (transform size)
 *   -DNTT_LOGN=4                    (log2 of size)
 *   -DNTT_PRIME=2013265921ULL       (field prime)
 *   -DNTT_GEN=31ULL                 (primitive root)
 *
 * Compile: clang -O2 -DNTT_FUNC=... -DNTT_SIZE=... ... -o test ntt.c harness_ntt.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#ifndef NTT_FUNC
#error "Define NTT_FUNC via -DNTT_FUNC=<name>"
#endif
#ifndef NTT_SIZE
#error "Define NTT_SIZE via -DNTT_SIZE=<n>"
#endif
#ifndef NTT_LOGN
#error "Define NTT_LOGN via -DNTT_LOGN=<logn>"
#endif
#ifndef NTT_PRIME
#error "Define NTT_PRIME via -DNTT_PRIME=<p>"
#endif
#ifndef NTT_GEN
#error "Define NTT_GEN via -DNTT_GEN=<g>"
#endif

/* Declare the generated NTT function */
void NTT_FUNC(int32_t* data, const int32_t* twiddles);

/* Declare the generated helpers */
extern uint64_t mod_pow(uint64_t base, uint64_t exp, uint64_t mod);
extern void compute_twiddles(uint32_t* tw, uint32_t* tw_mont, size_t n, size_t logn, uint64_t p, uint64_t gen);

int main(int argc, char* argv[]) {
    int n_args = argc - 1;
    if (n_args == 0 || n_args > NTT_SIZE) {
        fprintf(stderr, "Usage: %s <x0> [x1] ... (up to %d values)\n", argv[0], NTT_SIZE);
        return 1;
    }

    int32_t data[NTT_SIZE];
    for (int i = 0; i < NTT_SIZE; i++) data[i] = 0;
    for (int i = 0; i < n_args; i++)
        data[i] = (int32_t)atoll(argv[i + 1]);

    /* Compute twiddle factors (plain and Montgomery form) */
    uint32_t tw[NTT_SIZE * NTT_LOGN];
    uint32_t tw_mont[NTT_SIZE * NTT_LOGN];
    compute_twiddles(tw, tw_mont, NTT_SIZE, NTT_LOGN, NTT_PRIME, NTT_GEN);

    /* Run NTT with Montgomery twiddles */
    NTT_FUNC(data, (const int32_t*)tw_mont);

    /* Print output */
    for (int i = 0; i < NTT_SIZE; i++) {
        if (i > 0) printf(" ");
        printf("%d", data[i]);
    }
    printf("\n");
    return 0;
}
