/* Test harness for 4-element transforms generated by trzk.
 *
 * Reads 4 integers from command-line arguments, calls the generated
 * kernel, and prints the 4-element output. Used by verify_dft4.py
 * to check generated code against a reference implementation.
 *
 * Compile: clang -O2 -o dft4 dft4_spec.c harness_4.c
 */
#include <stdio.h>
#include <stdlib.h>

void dft4(double* restrict in, double* restrict out);

int main(int argc, char* argv[]) {
    if (argc != 5) {
        fprintf(stderr, "Usage: %s <x0> <x1> <x2> <x3>\n", argv[0]);
        return 1;
    }
    double inp[4], out[4];
    for (int i = 0; i < 4; i++)
        inp[i] = (double)atoll(argv[i + 1]);
    dft4(inp, out);
    printf("%lld %lld %lld %lld\n",
           (long long)out[0], (long long)out[1],
           (long long)out[2], (long long)out[3]);
    return 0;
}
