/* Test harness for Poseidon S-box generated by trzk.
 *
 * Reads one uint64 from argv, calls the S-box, prints the result.
 * The generated sbox5 function must be linked from the spec output.
 *
 * Compile: clang -O2 -o test_sbox spec.c harness_sbox.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

/* Declare the generated S-box — matches genSboxFunction output */
static inline uint64_t sbox5(uint64_t x);

/* The generated code defines sbox5 as static inline, so we include it */
#include "spec_sbox.c"

int main(int argc, char* argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <x>\n", argv[0]);
        return 1;
    }
    uint64_t x = strtoull(argv[1], NULL, 10);
    uint64_t result = sbox5(x);
    printf("%llu\n", (unsigned long long)result);
    return 0;
}
