/* Generic test harness for matrix transforms generated by trzk.
 *
 * Reads N integers from command-line arguments, calls the generated
 * kernel, and prints the N-element output.
 *
 * The function name is set via -DFUNC_NAME=<name> at compile time.
 * Compile: clang -O2 -DFUNC_NAME=dft4 -o test spec.c harness_matrix.c
 */
#include <stdio.h>
#include <stdlib.h>

#ifndef FUNC_NAME
#error "Define FUNC_NAME via -DFUNC_NAME=<name>"
#endif

/* Declare the generated function */
void FUNC_NAME(double* restrict in, double* restrict out);

int main(int argc, char* argv[]) {
    int n = argc - 1;
    if (n == 0) {
        fprintf(stderr, "Usage: %s <x0> [x1] [x2] ...\n", argv[0]);
        return 1;
    }
    double* inp = malloc(n * sizeof(double));
    double* out = malloc(n * sizeof(double));
    for (int i = 0; i < n; i++)
        inp[i] = (double)atoll(argv[i + 1]);
    FUNC_NAME(inp, out);
    for (int i = 0; i < n; i++) {
        if (i > 0) printf(" ");
        printf("%lld", (long long)out[i]);
    }
    printf("\n");
    free(inp);
    free(out);
    return 0;
}
