/* Test harness for N-element transforms generated by trzk.
 *
 * Reads N integers from command-line arguments, calls the generated
 * kernel, and prints the N-element output. Used by verify_dft.py to
 * check generated code against a reference implementation.
 *
 * Parameterized at compile time:
 *   -DN=<size>          size of the transform
 *   -DKERNEL=<symbol>   name of the generated kernel function
 *
 * Compile: clang -O2 -DN=4 -DKERNEL=dft4 -o dft4 dft4_spec.c harness.c
 */
#include <stdio.h>
#include <stdlib.h>

#ifndef N
#error "harness.c requires -DN=<size>"
#endif
#ifndef KERNEL
#error "harness.c requires -DKERNEL=<symbol>"
#endif

void KERNEL(double* restrict in, double* restrict out);

int main(int argc, char* argv[]) {
    if (argc != N + 1) {
        fprintf(stderr, "Usage: %s", argv[0]);
        for (int i = 0; i < N; i++) fprintf(stderr, " <x%d>", i);
        fprintf(stderr, "\n");
        return 1;
    }
    double inp[N], out[N];
    for (int i = 0; i < N; i++)
        inp[i] = (double)atoll(argv[i + 1]);
    KERNEL(inp, out);
    for (int i = 0; i < N; i++) {
        if (i > 0) putchar(' ');
        printf("%lld", (long long)out[i]);
    }
    putchar('\n');
    return 0;
}
